### PR TITLE
feat(SFINT-4203) Add loading spinner during user actions call

### PR DESCRIPTION
**Pull request by erocheleau**
fix deprecated sass lines
added loading spinner during user actions load

https://user-images.githubusercontent.com/2488155/151622401-0ddaaef2-7d2f-43d5-acd2-403c89b99d14.mp4

### CODE REVIEW

**Comment by erocheleau** [comment]
The loading spinner is coming from the SLDS open source GitHub repository:

https://github.com/salesforce-ux/design-system/tree/main/ui/components/spinners/base

**Comment by mikegron** [comment]
Tu vas ajouter un loading de Salesforce dans l'integration ServiceNow ? 😀🤔👨‍🌾

**Comment by erocheleau** [comment]
> Tu vas ajouter un loading de Salesforce dans l'integration ServiceNow ? 😀🤔👨‍🌾

Ben la c'est un spinner... does it matter?

**Comment by lbergeron** [comment]
> > Tu vas ajouter un loading de Salesforce dans l'integration ServiceNow ? grinningthinkingman_farmer
> 
> Ben la c'est un spinner... does it matter?

I think it does matter. Bringing Salesforce's styling in ServiceNow doesn't seem like a good idea to me either.

**Comment by erocheleau** [comment]
> > > Tu vas ajouter un loading de Salesforce dans l'integration ServiceNow ? grinningthinkingman_farmer
> > 
> > 
> > Ben la c'est un spinner... does it matter?
> 
> I think it does matter. Bringing Salesforce's styling in ServiceNow doesn't seem like a good idea to me either.

It's not styling, it's a spinner component/animation. I could've taken the spinner from another lib and it would be the same no?

**Review by mikegron — APPROVED** [review]

**Comment by lbergeron** [comment]
> > > > Tu vas ajouter un loading de Salesforce dans l'integration ServiceNow ? grinningthinkingman_farmer
> > > 
> > > 
> > > Ben la c'est un spinner... does it matter?
> > 
> > 
> > I think it does matter. Bringing Salesforce's styling in ServiceNow doesn't seem like a good idea to me either.
> 
> It's not styling, it's a spinner component/animation. I could've taken the spinner from another lib and it would be the same no?
> 
> My counter argument is that this is an extension to the JSUI, and in the JSUI we have plenty of Salesforce icons etc. So this is not like it's new that we are using Salesforce resources. And the loading is not branded Salesforce in any way.
> 
> So I could find a custom spinner on a blog post somewhere, or get one from another library, but this one is already built and clean to use.

Ok, given we're already using SLDS icons, adding the spinner is not an issue then.

**Review by lbergeron — APPROVED** [review]

**Comment by lvu285** [comment]
are we going to have automated tests to cover for this one?

**Review by lvu285 — APPROVED** [review]

**Review by mmitiche — APPROVED** [review]
👌👌

**Pull request merged**
